name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Java environment
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle environment
        uses: gradle/actions/setup-gradle@v5

      - name: Extract Minecraft Version via Gradle
        id: get_version
        run: |
          VERSION=$(./gradlew --quiet showMinecraftVersion)
          echo "minecraft_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate Data Files
        run: |
          set -eu
          mkdir -p run
          echo 'eula=true' > run/eula.txt
          ./gradlew --console plain --no-daemon runServer

      - name: Update Release and Tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.minecraft_version }}
          name: Minecraft ${{ steps.get_version.outputs.minecraft_version }}
          body: |
            ### ðŸŽ¨ Palette Data
            Automated export of map color data for **Minecraft ${{ steps.get_version.outputs.minecraft_version }}**.

            #### ðŸ“¦ Contents
            * `colors.csv`: RGB values for all map colors (including shade variants).
            * `blocks.csv`: Mappings of block IDs to base map colors.

            > See the project [README](https://github.com/${{ github.repository }}) for usage and format details.
          allowUpdates: true
          removeArtifacts: true
          makeLatest: true
          artifacts: 'run/palette/colors.csv,run/palette/blocks.csv'
          token: ${{ secrets.GITHUB_TOKEN }}
